apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gitops-lab-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: task-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
                  
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_URI
          
          livenessProbe:
            httpGet:
              path: /api/tasks
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /api/tasks
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gitops-lab-ns
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
    