apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-notifications
  namespace: monitoring
  labels:
    alertmanagerConfig: monitoring

spec:
  route:
    receiver: discord

  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: 'webhook-url'